spring.application.name=gateway
server.port = 8084

# Zipkin tracing
management.tracing.sampling.probability = 1.0

# Eureka configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#jwt secret
jwt.secret = eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcyNTkxMDAyNywiaWF0IjoxNzI1OTEwMDI3fQ.6URB1MESywJ-lrcUiqwDarvX68QrnowrrHv0LhfmDXE

# PRODUCT-SERVICE routes
## Public routes
spring.cloud.gateway.routes[0].id=public_product_service
spring.cloud.gateway.routes[0].uri=lb://PRODUCTS-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/public/products/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=0

## Admin routes
spring.cloud.gateway.routes[1].id=admin_product_service
spring.cloud.gateway.routes[1].uri=lb://PRODUCTS-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/admin/products/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=0

## Seller routes
spring.cloud.gateway.routes[2].id=seller_product_service
spring.cloud.gateway.routes[2].uri=lb://PRODUCTS-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/seller/products/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=0

## User routes
spring.cloud.gateway.routes[3].id=user_product_service
spring.cloud.gateway.routes[3].uri=lb://PRODUCTS-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/user/products/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=0

# INVENTORYITEM-SERVICE routes
## Public routes
spring.cloud.gateway.routes[4].id=public_inventoryitem_service
spring.cloud.gateway.routes[4].uri=lb://INVENTORYITEM-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/public/inventoryItems/**
spring.cloud.gateway.routes[4].filters[0]=StripPrefix=0

## Admin routes
spring.cloud.gateway.routes[5].id=admin_inventoryitem_service
spring.cloud.gateway.routes[5].uri=lb://INVENTORYITEM-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/admin/inventoryItems/**
spring.cloud.gateway.routes[5].filters[0]=StripPrefix=0

## Seller routes
spring.cloud.gateway.routes[6].id=seller_inventoryitem_service
spring.cloud.gateway.routes[6].uri=lb://INVENTORYITEM-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/seller/inventoryItems/**
spring.cloud.gateway.routes[6].filters[0]=StripPrefix=0

## User routes
spring.cloud.gateway.routes[7].id=user_inventoryitem_service
spring.cloud.gateway.routes[7].uri=lb://INVENTORYITEM-SERVICE
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/user/inventoryItems/**
spring.cloud.gateway.routes[7].filters[0]=StripPrefix=0

# CATEGORY-SERVICE routes
## Public routes
spring.cloud.gateway.routes[8].id=public_category_service
spring.cloud.gateway.routes[8].uri=lb://CATEGORY-SERVICE
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/v1/public/categories/**
spring.cloud.gateway.routes[8].filters[0]=StripPrefix=0

## Admin routes
spring.cloud.gateway.routes[9].id=admin_category_service
spring.cloud.gateway.routes[9].uri=lb://CATEGORY-SERVICE
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/v1/admin/categories/**
spring.cloud.gateway.routes[9].filters[0]=StripPrefix=0

## Seller routes
spring.cloud.gateway.routes[10].id=seller_category_service
spring.cloud.gateway.routes[10].uri=lb://CATEGORY-SERVICE
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/v1/seller/categories/**
spring.cloud.gateway.routes[10].filters[0]=StripPrefix=0

## User routes
spring.cloud.gateway.routes[11].id=user_category_service
spring.cloud.gateway.routes[11].uri=lb://CATEGORY-SERVICE
spring.cloud.gateway.routes[11].predicates[0]=Path=/api/v1/user/categories/**
spring.cloud.gateway.routes[11].filters[0]=StripPrefix=0

# AUTH-SERVICE routes
## Public auth routes
spring.cloud.gateway.routes[12].id=public_auth_service
spring.cloud.gateway.routes[12].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[12].predicates[0]=Path=/api/v1/auth/**
spring.cloud.gateway.routes[12].filters[0]=StripPrefix=0

## Private address routes
spring.cloud.gateway.routes[13].id=private_address_service
spring.cloud.gateway.routes[13].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[13].predicates[0]=Path=/api/v1/user/**
spring.cloud.gateway.routes[13].filters[0]=StripPrefix=0

## Public seller by category routes
spring.cloud.gateway.routes[14].id=public_seller_by_category_service
spring.cloud.gateway.routes[14].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[14].predicates[0]=Path=/api/v1/seller/byCategory/**
spring.cloud.gateway.routes[14].filters[0]=StripPrefix=0

# Updated Swagger UI Configuration
springdoc.swagger-ui.urls[0].url=/api/v1/public/products/api-docs
springdoc.swagger-ui.urls[0].name=Products Service
springdoc.swagger-ui.urls[1].url=/api/v1/public/inventoryItems/api-docs
springdoc.swagger-ui.urls[1].name=Inventory Item Service
springdoc.swagger-ui.urls[2].url=/api/v1/public/categories/api-docs
springdoc.swagger-ui.urls[2].name=Category Service
springdoc.swagger-ui.urls[3].url=/api/v1/public/auth/api-docs
springdoc.swagger-ui.urls[3].name=Auth Service


# Routes for Swagger docs
spring.cloud.gateway.routes[15].id=swagger-products
spring.cloud.gateway.routes[15].uri=http://localhost:8081
spring.cloud.gateway.routes[15].predicates[0]=Path=/api/v1/public/products/api-docs
spring.cloud.gateway.routes[15].filters[0]=RewritePath=/api/v1/public/products/api-docs, /v3/api-docs

spring.cloud.gateway.routes[16].id=swagger-inventoryitem
spring.cloud.gateway.routes[16].uri=http://localhost:8082
spring.cloud.gateway.routes[16].predicates[0]=Path=/api/v1/public/inventoryItems/api-docs
spring.cloud.gateway.routes[16].filters[0]=RewritePath=/api/v1/public/inventoryItems/api-docs, /v3/api-docs

spring.cloud.gateway.routes[17].id=swagger-category
spring.cloud.gateway.routes[17].uri=lb://CATEGORY-SERVICE
spring.cloud.gateway.routes[17].predicates[0]=Path=/api/v1/public/categories/api-docs
spring.cloud.gateway.routes[17].filters[0]=RewritePath=/api/v1/public/categories/api-docs, /v3/api-docs

spring.cloud.gateway.routes[18].id=swagger-auth
spring.cloud.gateway.routes[18].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[18].predicates[0]=Path=/api/v1/public/auth/api-docs
spring.cloud.gateway.routes[18].filters[0]=RewritePath=/api/v1/public/auth/api-docs, /v3/api-docs


# Enable discovery of API documentation
springdoc.enable-native-support=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.urls-primary-name=API Gateway